"""
Pydantic schemas for the MoES Desktop Software.

Data provenance is always explicit:
  MEASURED   — direct sensor reading imported from firmware CSV/JSON
  CALCULATED — derived mathematically from measured data (e.g., drift distance)
  INFERRED   — output of a heuristic rule (e.g., evidence_score, classification)
  DEMO       — generated by the synthetic demo-data generator

Evidence / Confidence Score:
  A heuristic score in [0, 1].  Rule-based, NOT a statistically calibrated probability.

Mineral classification terminology is conservative:
  POSSIBLE_METALLIC_ANOMALY | POSSIBLE_THERMAL_ANOMALY |
  POSSIBLE_HYDROTHERMAL_ASSOCIATED_ANOMALY | MULTISENSOR_ANOMALY |
  INSUFFICIENT_DATA
"""

from __future__ import annotations

import enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class DataProvenance(str, enum.Enum):
    MEASURED   = "MEASURED"
    CALCULATED = "CALCULATED"
    INFERRED   = "INFERRED"
    DEMO       = "DEMO"


class AnomalyType(str, enum.Enum):
    POSSIBLE_METALLIC_ANOMALY               = "POSSIBLE_METALLIC_ANOMALY"
    POSSIBLE_THERMAL_ANOMALY                = "POSSIBLE_THERMAL_ANOMALY"
    POSSIBLE_HYDROTHERMAL_ASSOCIATED_ANOMALY = "POSSIBLE_HYDROTHERMAL_ASSOCIATED_ANOMALY"
    MULTISENSOR_ANOMALY                     = "MULTISENSOR_ANOMALY"
    INSUFFICIENT_DATA                       = "INSUFFICIENT_DATA"
    NONE                                    = "NONE"


class ValidationStatus(str, enum.Enum):
    OK      = "OK"
    WARNING = "WARNING"
    ERROR   = "ERROR"


# ---------------------------------------------------------------------------
# Raw telemetry (one row from ESP32 CSV/JSON)
# ---------------------------------------------------------------------------

class TelemetryRecord(BaseModel):
    """One sample row from the ESP32 telemetry log."""

    # --- Timestamps ---
    timestamp_unix: Optional[float] = Field(None, description="Unix epoch seconds (MEASURED)")
    timestamp_rtc:  Optional[str]   = Field(None, description="ISO-8601 string from DS3231 (MEASURED)")

    # --- Validity flags (from firmware) ---
    imu_valid:    Optional[bool] = None
    pt100_valid:  Optional[bool] = None
    mag_valid:    Optional[bool] = None
    pi_valid:     Optional[bool] = None
    rtc_valid:    Optional[bool] = None
    gps_valid:    Optional[bool] = None

    # --- IMU (MPU6050) ---
    accel_x_g:        Optional[float] = None
    accel_y_g:        Optional[float] = None
    accel_z_g:        Optional[float] = None
    gyro_x_dps:       Optional[float] = None
    gyro_y_dps:       Optional[float] = None
    gyro_z_dps:       Optional[float] = None
    imu_die_temp_c:   Optional[float] = Field(None, description="MPU6050 internal die temperature (MEASURED)")

    # --- Water temperature (PT100 / MAX31865) ---
    water_temp_c:     Optional[float] = Field(None, description="PT100 water temperature (MEASURED)")

    # --- Magnetic (RM3100) ---
    mag_x_ut:   Optional[float] = None
    mag_y_ut:   Optional[float] = None
    mag_z_ut:   Optional[float] = None

    # --- Pulse-induction decay ---
    pi_baseline:        Optional[float] = None
    pi_peak:            Optional[float] = None
    pi_early_decay:     Optional[float] = None
    pi_late_decay:      Optional[float] = None
    pi_anomaly_strength: Optional[float] = None

    # --- Fusion outputs ---
    roll_deg:    Optional[float] = None
    pitch_deg:   Optional[float] = None
    heading_deg: Optional[float] = None
    drift_north_m: Optional[float] = None
    drift_east_m:  Optional[float] = None
    deployment_drift_radius_m: Optional[float] = None

    # --- GPS (if present) ---
    latitude:  Optional[float] = None
    longitude: Optional[float] = None

    # Provenance
    data_provenance: DataProvenance = DataProvenance.MEASURED

    # Allow extra columns from the CSV without failing
    model_config = {"extra": "allow"}


# ---------------------------------------------------------------------------
# Deployment metadata (supplied by operator at upload time)
# ---------------------------------------------------------------------------

class DeploymentMetadata(BaseModel):
    """Operator-supplied metadata for one deployment / survey station."""

    station_id:         str   = Field(..., description="Unique station identifier")
    deploy_latitude:    float = Field(..., ge=-90,  le=90)
    deploy_longitude:   float = Field(..., ge=-180, le=180)
    deploy_depth_m:     Optional[float] = Field(None, ge=0)
    operator_notes:     Optional[str]   = None
    drift_scale_m:      float = Field(400.0, ge=0,
        description="Maximum expected drift radius (m). "
                    "Used as uncertainty extent, NOT exact target position.")
    demo_mode:          bool  = False
    data_provenance:    DataProvenance = DataProvenance.MEASURED


# ---------------------------------------------------------------------------
# Validation report
# ---------------------------------------------------------------------------

class FieldIssue(BaseModel):
    field:   str
    row:     Optional[int] = None
    message: str
    status:  ValidationStatus


class ValidationReport(BaseModel):
    station_id:    str
    total_rows:    int
    valid_rows:    int
    issues:        List[FieldIssue] = []
    overall_status: ValidationStatus = ValidationStatus.OK
    data_provenance: DataProvenance  = DataProvenance.MEASURED


# ---------------------------------------------------------------------------
# Feature vector (per deployment, summarises one sensor channel)
# ---------------------------------------------------------------------------

class SensorFeatures(BaseModel):
    """Statistical summary of one sensor channel over a deployment."""

    station_id:      str
    channel:         str
    n_samples:       int
    mean:            Optional[float] = None
    std:             Optional[float] = None
    min_val:         Optional[float] = None
    max_val:         Optional[float] = None
    p5:              Optional[float] = None
    p95:             Optional[float] = None
    n_valid:         int = 0
    data_provenance: DataProvenance = DataProvenance.CALCULATED


# ---------------------------------------------------------------------------
# Anomaly detection result
# ---------------------------------------------------------------------------

class AnomalyFlag(BaseModel):
    """Result of one anomaly detector for one channel."""

    station_id:        str
    channel:           str
    detector:          str  = Field(..., description="Name of the detector rule used")
    is_anomalous:      bool
    trigger_value:     Optional[float] = None
    threshold_used:    Optional[float] = None
    description:       str  = ""
    data_provenance:   DataProvenance  = DataProvenance.INFERRED


# ---------------------------------------------------------------------------
# Classification result
# ---------------------------------------------------------------------------

class ClassificationResult(BaseModel):
    """
    Evidence-based anomaly classification.

    evidence_score:
        Heuristic score in [0, 1].
        Rule-based, NOT a statistically calibrated probability.
        UI label: 'Evidence / Confidence Score'.
    """

    station_id:       str
    anomaly_type:     AnomalyType
    evidence_score:   float = Field(..., ge=0.0, le=1.0,
        description="Heuristic evidence score [0-1]. Rule-based, NOT statistically calibrated.")
    contributing_channels: List[str] = []
    rationale:        str  = ""
    data_provenance:  DataProvenance = DataProvenance.INFERRED

    @field_validator("evidence_score")
    @classmethod
    def clamp_score(cls, v: float) -> float:
        return max(0.0, min(1.0, round(v, 4)))


class AnomalyEvent(BaseModel):
    """One localized anomaly window derived from telemetry observations."""

    station_id: str
    start_timestamp: str
    end_timestamp: str
    representative_timestamp: str
    latitude: float
    longitude: float
    pi_strength: Optional[float] = None
    temperature: Optional[float] = None
    temperature_delta: Optional[float] = None
    magnetic_strength: Optional[float] = None
    heading: Optional[float] = None
    evidence_score: float = Field(0.0, ge=0.0, le=1.0)
    classification: AnomalyType = AnomalyType.INSUFFICIENT_DATA
    evidence_flags: List[str] = []
    data_provenance: DataProvenance = DataProvenance.INFERRED


# ---------------------------------------------------------------------------
# Geodesic localisation
# ---------------------------------------------------------------------------

class DriftSector(BaseModel):
    """
    Uncertainty sector polygon around a deployment point.

    The sector covers the area within drift_scale_m of the deployment point
    in the direction of measured drift.  It is an uncertainty extent,
    NOT a pinpoint target location.
    """

    station_id:          str
    deploy_latitude:     float
    deploy_longitude:    float
    drift_bearing_deg:   Optional[float] = None
    drift_distance_m:    Optional[float] = None
    sector_half_angle_deg: float = 45.0
    drift_scale_m:       float  = 400.0
    sector_geojson:      Optional[Dict[str, Any]] = None
    data_provenance:     DataProvenance = DataProvenance.CALCULATED


# ---------------------------------------------------------------------------
# Multi-station candidate
# ---------------------------------------------------------------------------

class MultiStationCandidate(BaseModel):
    """
    A candidate anomaly zone identified by overlapping sectors
    from ≥2 stations.

    candidate_score:
        Documented heuristic combining station evidence scores,
        spatial overlap fraction, and data quality.
        NOT computed as 1-(1-Ca)(1-Cb).
        NOT a probability.
    """

    candidate_id:     str
    station_ids:      List[str]
    centroid_lat:     float
    centroid_lon:     float
    overlap_area_m2:  Optional[float] = None
    overlap_geojson:  Optional[Dict[str, Any]] = None
    station_scores:   Dict[str, float] = {}
    candidate_score:  float = Field(..., ge=0.0, le=1.0,
        description="Heuristic candidate score. NOT a probability formula.")
    classification:   AnomalyType = AnomalyType.INSUFFICIENT_DATA
    data_provenance:  DataProvenance = DataProvenance.INFERRED


# ---------------------------------------------------------------------------
# Heatmap point
# ---------------------------------------------------------------------------

class HeatmapPoint(BaseModel):
    """
    One grid cell in the IDW-interpolated heatmap.
    Values are interpolated — NOT direct measurements.
    UI label: 'Interpolated anomaly intensity'.
    """

    lat:             float
    lon:             float
    value:           float
    data_provenance: DataProvenance = DataProvenance.INFERRED  # interpolated = inferred


# ---------------------------------------------------------------------------
# Export bundle
# ---------------------------------------------------------------------------

class ExportBundle(BaseModel):
    """Top-level export for SIH demonstration."""

    export_version:      str = "1.0"
    generated_at:        str = ""
    stations:            List[DeploymentMetadata]       = []
    validation_reports:  List[ValidationReport]         = []
    classifications:     List[ClassificationResult]     = []
    anomaly_events:      List[AnomalyEvent]              = []
    drift_sectors:       List[DriftSector]              = []
    candidates:          List[MultiStationCandidate]    = []
    heatmap_points:      List[HeatmapPoint]             = []
    notes:               str = (
        "evidence_score is a rule-based heuristic, NOT a statistically calibrated probability. "
        "Classification labels (POSSIBLE_*) indicate anomaly type indication only; "
        "no exact mineral identification is claimed."
    )
